@baseUrl = http://localhost:3000


# Messages

### Create
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "text": "This message 3",
  "fromId":5,
  "toId": 3
}

### All
GET {{baseUrl}}/messages
# ?limit=10
# &offset=10

### One
GET {{baseUrl}}/messages/5

### Edit
PATCH {{baseUrl}}/messages/2
Content-Type: application/json

{
  "text": "Text changed",
}

### Delete
DELETE {{baseUrl}}/messages/1


# People

### Create
POST {{baseUrl}}/people
Content-Type: application/json

{
  "email": "leo@email.com",
  "name": "Leo",
  "password": "5678910"
}

### All
GET {{baseUrl}}/people

### One
GET {{baseUrl}}/people/1

### Edit
PATCH {{baseUrl}}/people/3
Content-Type: application/json

{
  "name": "João S. Atualizado",
  "email":"new@gmail.com"
}

### Delete
DELETE {{baseUrl}}/people/1