@baseUrl = http://localhost:3000


# Messages

### Create
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "text": "This message 3",
  "from": "John Doe",
  "to": "Jane Doe"
}

### All
GET {{baseUrl}}/messages
# ?limit=10
# &offset=10

### One
GET {{baseUrl}}/messages/1

### Edit
PATCH {{baseUrl}}/messages/2
Content-Type: application/json

{
  "text": "Text changed",
}

### Delete
DELETE {{baseUrl}}/messages/1


# People

### Create
POST {{baseUrl}}/people
Content-Type: application/json

{
  "email": "joao@email.com",
  "name": "João Silva",
  "password": "123456"
}

### All
GET {{baseUrl}}/people

### One
GET {{baseUrl}}/people/1

### Edit
PATCH {{baseUrl}}/people/1
Content-Type: application/json

{
  "name": "João S. Atualizado"
}

### Delete
DELETE {{baseUrl}}/people/1